# 
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: ground_ref/pose
        pose2d: ground_ref/ground_pose
        markers: ground_ref/markers
        frame_id: ground_ref/base_link